name = "QDOptimization"
uuid = "ea172223-2b79-40f8-9edf-9edbf12dcd2d"
authors = ["Powers, Joshua <dev@powerslabs.org>"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
